const BONEID_RIGHT_HAND = 57005;

const registeredObjects = {
    'phone': { objectName: 'p_amb_phone_01', boneId: BONEID_RIGHT_HAND, position: { x: 0.15, y: 0.0, z: -0.043, }, rotation: { x: 15.0, y: 80.0, z: 150 }, 
        enterAnimation: {dict: '', name: '', flag: '', durationMs: ''},
        exitAnimation: {dict: '', name: '', flag: '', durationMs: '' } },
    'tablet': { objectName: 'prop_cs_tablet', boneId: 60309, position: { x: 0.03, y: -0.000, z: 0, }, rotation: { x: 10, y: 0, z: -10},
        enterAnimation: {dict: 'amb@code_human_in_bus_passenger_idles@female@tablet@base', name: 'base', flag: 49, durationMs: 0 },
        exitAnimation: {dict: '', name: '', flag: 49, durationMs: 0 } },
    'bottle': { objectName: 'prop_beer_bottle', boneId: BONEID_RIGHT_HAND, position: { x: 0.13, y: -0.12, z: -0.05, }, rotation: { x: 100, y: -220, z: 180},
        enterAnimation: {dict: 'amb@world_human_drinking@beer@male@idle_a', name: 'idle_c', flag: 49, durationMs: 5000 },
        exitAnimation: {dict: '', name: '', flag: 49, durationMs: 0 } },
    'orange': { objectName: 'ng_proc_food_ornge1a', boneId: BONEID_RIGHT_HAND, position: { x: 0.16, y: 0.01, z: -0.01, }, rotation: { x: -15, y: -150, z: -95},
        enterAnimation: {dict: 'amb@code_human_wander_eating_donut@male@idle_a', name: 'idle_c', flag: 49, durationMs: 5000 },
        exitAnimation: {dict: '', name: '', flag: 49, durationMs: 0 } },
    'burger': { objectName: 'prop_cs_burger_01', boneId: BONEID_RIGHT_HAND, position: { x: 0.15, y: -0.02, z: -0.05, }, rotation: { x: -180, y: -150, z: -95},
        enterAnimation: {dict: '', name: '', flag: '', durationMs: '' },
        exitAnimation: {dict: '', name: '', flag: 49, durationMs: 0 } },
    'fishing-rod': { objectName: 'prop_fishing_rod_01', boneId: 60309, position: { x: 0, y: -0.01, z: 0.01, }, rotation: { x: -180, y: -185, z: -175},
        enterAnimation: { dict: 'amb@world_human_stand_fishing@idle_a', name: 'idle_c', flag: 15, durationMs: 0 },
        exitAnimation: { dict: '', name: '', flag: 15, durationMs: 0 } },
    'bottle2': { objectName: 'ba_prop_club_water_bottle', boneId: 18905, position: { x: 0.09, y: -0.08, z: 0.08, }, rotation: { x: 55, y: -220, z: 180},
        enterAnimation: { dict: '', name: '', flag: '', durationMs:'' },
        exitAnimation: { dict: '', name: '', flag: 49, durationMs: 0 } },
    'burger2': { objectName: 'prop_cs_burger_01', boneId: 18905, position: { x: 0.14, y: 0.02, z: 0.03, }, rotation: { x: -45, y: 130, z: -95},
        enterAnimation: { dict: '', name: '', flag: '', durationMs:''},
        exitAnimation: { dict: '', name: '', flag: 49, durationMs: 0 } },
    'broom': { objectName: 'prop_tool_broom', boneId: 18905, position: { x: 0.16, y: 0.05, z: -0.01, }, rotation: { x: 25, y: -95, z: 30},
        enterAnimation: { dict: '', name: '', flag: '', durationMs:''},
        exitAnimation: { dict: '', name: '', flag: 49, durationMs: 0 } },
    'weapon-chest-pistol': { objectName: 'xm_prop_x17_chest_open', boneId: 14201, position: { x: 0.66, y: 0.14, z: 0.24, }, rotation: { x: 100, y: 90, z: -180},
        enterAnimation: { dict: '', name: '', flag: 15, durationMs: 0 },
        exitAnimation: { dict: '', name: '', flag: 15, durationMs: 0 } },
    'weapon-chest-rifle': { objectName: 'prop_gun_case_02', boneId: 14201, position: { x: 0.52, y: 0.18, z: 0.34, }, rotation: { x: 110, y: 75, z: -175},
        enterAnimation: { dict: '', name: '', flag: 15, durationMs: 0 },
        exitAnimation: { dict: '', name: '', flag: 15, durationMs: 0 } },
    'reload-pistol': { objectName: 'w_pi_heavypistol_luxe', boneId: 57005, position: { x: 0.19, y: 0.03, z: 0.01, }, rotation: { x: 105, y: -205, z: 185},
        enterAnimation: { dict: '', name: '', flag: 49, durationMs: 0 },
        exitAnimation: { dict: '', name: '', flag: 49, durationMs: 0 } },
    'reload-rifle': { objectName: 'w_ar_advancedrifle_luxe', boneId: 57005, position: { x: 0.14, y: 0.03, z: -0.02, }, rotation: { x: -100, y: -5, z: 0},
        enterAnimation: { dict: '', name: '', flag: 49, durationMs: 0 },
        exitAnimation: { dict: '', name: '', flag: 49, durationMs: 0 } },
    'cuffings': { objectName: 'prop_cs_cuffs_01', boneId: 57005, position: { x: 0.09, y: -0.02, z: 0, }, rotation: { x: -275, y: -150, z: -95},
        enterAnimation: { dict: '', name: '', flag: 49, durationMs: 0 },
        exitAnimation: { dict: '', name: '', flag: 49, durationMs: 0 } },
    'cuffed-back': { objectName: 'h4_prop_battle_cuffs', boneId: 57005, position: { x: 0.01, y: 0.07, z: -0.02, }, rotation: { x: -45, y: -150, z: -80},
        enterAnimation: { dict: '', name: '', flag:'', durationMs: 0 },
        exitAnimation: { dict: '', name: '', flag:'',  durationMs: 0 } },
    'cuffed-front': { objectName: 'p_cs_cuffs_02_s', boneId: 18905, position: { x: 0.01, y: 0.01, z: 0.05, }, rotation: { x: -190, y: -90, z: 0},
        enterAnimation: { dict: '', name: '', flag: '', durationMs: 0 },
        exitAnimation: { dict: '', name: '', flag: '', durationMs: 0 } },
    'phone2': { objectName: 'p_amb_phone_01', boneId: 57005, position: { x: 0.13, y: 0, z: -0.04, }, rotation: { x: 20, y: 65, z: 85},
        enterAnimation: { dict: '', name: '', flag: '', durationMs: '' },
        exitAnimation: { dict: '', name: '', flag: '', durationMs: '' } },
    'tablet': { objectName: 'prop_cs_tablet', boneId: 57005, position: { x: 0.16, y: 0, z: -0.06, }, rotation: { x: 15, y: 80, z: 150},
        enterAnimation: { dict: '', name: '', flag: '', durationMs: '' },
        exitAnimation: { dict: '', name: '', flag: '', durationMs: '' } },
    'binbag': { objectName: 'ng_proc_binbag_02a', boneId: 57005, position: { x: 0.07, y: -0.28, z: 0.25, }, rotation: { x: 130, y: -50, z: -125},
        enterAnimation: { dict: '', name: '', flag: '', durationMs: '' },
        exitAnimation: { dict: '', name: '', flag: '', durationMs: '' } },
    'Jackhammer': { objectName: 'prop_tool_jackham', boneId: 0, position: { x: 0, y: 0.29, z: -0.03, }, rotation: { x: 0, y: 0, z: 0},
        enterAnimation: { dict: '', name: 'world_human_const_drill_lo_res_base', flag: 49, durationMs: 0 },
        exitAnimation: { dict: '', name: '', flag: 49, durationMs: 0 } },
    'Bucket': { objectName: 'prop_bucket_02a', boneId: 46078, position: { x: 0.21, y: 0.44, z: 0.03, }, rotation: { x: -55, y: -135, z: -45},
        enterAnimation: { dict: '', name: '', flag: 49, durationMs: 0 },
        exitAnimation: { dict: '', name: '', flag: 49, durationMs: 0 } },
    'Pickaxe': { objectName: 'prop_tool_pickaxe', boneId: 57005, position: { x: 0.03, y: -0.25, z: -0.12, }, rotation: { x: -70, y: 0, z: -15},
        enterAnimation: { dict: '', name: '', flag: 49, durationMs: 0 },
        exitAnimation: { dict: '', name: '', flag: 49, durationMs: 0 } },
    'Axe': { objectName: 'prop_tool_fireaxe', boneId: 57005, position: { x: 0.15, y: -0.07, z: -0.07, }, rotation: { x: 50, y: -30, z: 190},
        enterAnimation: { dict: '', name: '', flag: 49, durationMs: 0 },
        exitAnimation: { dict: '', name: '', flag: 49, durationMs: 0 } },
    'trowel': { objectName: 'prop_cs_trowel', boneId: 57005, position: { x: 0.08, y: -0.03, z: -0.05, }, rotation: { x: 110, y: 90, z: 16},
        enterAnimation: { dict: '', name: '', flag: 49, durationMs: 0 },
        exitAnimation: { dict: '', name: '', flag: 49, durationMs: 0 } }
};

export default registeredObjects;